import { createError, getQuery } from 'h3'
import { kvGet, kvPut } from '../../../utils/kv'
import { getSelectedTenant } from '../../../utils/session'
import { GROQ_MODELS } from '../../../utils/groqClient'
import { generateModelRoutedGroqInsight } from '../../../utils/ai/resolvedGroq'

/**
 * Owner-focused AI briefing for /invoices.
 *
 *   GET /api/xero/invoices/ai-briefing?refresh=1
 *
 * Returns a short executive narrative + up-to-2 actions, generated by
 * Groq from the existing /api/xero/invoices summary. Cached per-tenant
 * for 1 hour so we don't burn tokens on every page load. `?refresh=1`
 * forces regeneration.
 *
 * Output shape:
 *   {
 *     headline: string                        // one line, scan-friendly
 *     narrative: string                       // 2-3 sentences, names specifics
 *     actions: { label: string; why?: string }[]   // 0-2 items
 *     riskLevel: 'low' | 'moderate' | 'high'
 *     generatedAt: ISO string
 *     cached: boolean
 *   }
 *
 * Hand-written rule for "not enough data" → returns a short canned
 * response without calling Groq. Saves tokens and prevents hallucinated
 * narratives on empty AR.
 */

interface BriefingPayload {
  outstandingTotal?: number
  outstandingCount?: number
  overdueTotal?: number
  overdueCount?: number
  dso30?: number | null
  notSentCount?: number
  notSentTotal?: number
  paidLast30Total?: number
  avgDaysToPay?: number | null
  concentration?: { top1Pct: number; top3Pct: number; top1Name: string | null; riskLevel: string; customerCount: number }
  topCustomers?: Array<{ name: string; outstanding: number; overdue: number; pctOfAr: number }>
  latePayers?: Array<{ name: string; avgDaysToPay: number; openOverdue: number; paidCount: number }>
  cashForecast?: { next30Total: number; buckets: Array<{ key: string; total: number; count: number }> }
  recurringMrr?: number
  creditNotesTotal?: number
}

const SYSTEM_PROMPT = `You are an experienced agency-owner CFO advisor. You receive an accounts-receivable snapshot and produce a tight executive briefing.

Hard rules:
- Output VALID JSON ONLY matching the schema. No prose outside JSON.
- Identify the SINGLE biggest issue and 1-2 actions. Don't restate every metric.
- Reference customer names from the data (don't fabricate).
- If everything looks fine, say so. Don't invent problems.
- Narrative: 2-3 sentences, plain English, no jargon dumps.
- Each action is verb-led, concrete, executable from this dashboard, with a brief "why".
- riskLevel: "high" if cash position is at risk (DSO>45, top1>30%, big chronic late payer with sizeable balance), "moderate" if 1-2 yellow flags, "low" otherwise.

Schema:
{
  "headline": "≤80 char one-liner, no period at end",
  "narrative": "2-3 sentences",
  "actions": [{"label": "verb-led action", "why": "why this matters"}],
  "riskLevel": "low" | "moderate" | "high"
}`

function buildPrompt(payload: BriefingPayload): string {
  // Compact, structured input — easier for the model than prose.
  return `AR snapshot for an Australian agency. All amounts AUD.

Open AR: $${payload.outstandingTotal?.toLocaleString() ?? 0} across ${payload.outstandingCount ?? 0} invoices.
Overdue: $${payload.overdueTotal?.toLocaleString() ?? 0} across ${payload.overdueCount ?? 0} invoices.
Not yet sent (created but not emailed): ${payload.notSentCount ?? 0} invoices, $${payload.notSentTotal?.toLocaleString() ?? 0}.
Paid last 30 days: $${payload.paidLast30Total?.toLocaleString() ?? 0}.
DSO (30d): ${payload.dso30 ?? 'unknown'} days. (Healthy <30, watch 30-45, risk >45.)
Avg days to pay (paid invoices): ${payload.avgDaysToPay ?? 'unknown'}.
Recurring monthly revenue: $${payload.recurringMrr?.toLocaleString() ?? 0}.
Outstanding credit notes (owed back to customers): $${payload.creditNotesTotal?.toLocaleString() ?? 0}.

Customer concentration:
- Top 1: ${payload.concentration?.top1Name ?? 'unknown'} at ${payload.concentration?.top1Pct ?? 0}% of AR
- Top 3 share: ${payload.concentration?.top3Pct ?? 0}%
- Total clients with outstanding balances: ${payload.concentration?.customerCount ?? 0}
- Built-in risk level: ${payload.concentration?.riskLevel ?? 'unknown'}

Top outstanding clients:
${(payload.topCustomers ?? []).slice(0, 5).map(c => `- ${c.name}: $${c.outstanding.toLocaleString()} outstanding ($${c.overdue.toLocaleString()} overdue), ${c.pctOfAr}% of AR`).join('\n') || '(none)'}

Chronic late payers (avg days to pay across paid history):
${(payload.latePayers ?? []).slice(0, 5).map(p => `- ${p.name}: ${p.avgDaysToPay}d avg (${p.paidCount} paid invoices), $${p.openOverdue.toLocaleString()} currently overdue`).join('\n') || '(none)'}

Cash collection next 30 days: $${payload.cashForecast?.next30Total?.toLocaleString() ?? 0} expected.

Produce the JSON briefing now.`
}

function tryParseJson(raw: string): any | null {
  try {
    return JSON.parse(raw)
  } catch {
    // Models occasionally wrap JSON in ```json fences — strip and retry.
    const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/)
    if (fenced) {
      try { return JSON.parse(fenced[1]) } catch { /* fall through */ }
    }
    // Or extract from `{ ... }` substring.
    const first = raw.indexOf('{')
    const last = raw.lastIndexOf('}')
    if (first !== -1 && last > first) {
      try { return JSON.parse(raw.slice(first, last + 1)) } catch { /* fall through */ }
    }
    return null
  }
}

export default eventHandler(async (event) => {
  const tenantId = await getSelectedTenant(event)
  if (!tenantId) {
    throw createError({ statusCode: 400, statusMessage: 'No organization selected' })
  }

  const q = getQuery(event)
  const refresh = q.refresh === '1' || q.refresh === 'true'
  const cacheKey = `xero:ai-briefing:${tenantId}`

  // Cached path — instant return.
  if (!refresh) {
    const cached = await kvGet<any>(event, cacheKey)
    if (cached?.headline) {
      return { ...cached, cached: true }
    }
  }

  // Fetch the rich summary by hitting our own /api/xero/invoices.
  // This reuses the cachedFetch-driven full-pipe of pagination,
  // aggregation, and reminder annotation — much cheaper than re-doing
  // it here.
  const invoiceData = await $fetch<any>('/api/xero/invoices', {
    headers: {
      cookie: event.node.req.headers.cookie || '',
    },
  })
  const summary = invoiceData?.summary

  if (!summary) {
    throw createError({ statusCode: 502, statusMessage: 'Could not load invoice summary' })
  }

  // Short-circuit on empty AR — don't burn tokens hallucinating about a
  // company with no invoices.
  if ((summary.outstandingCount ?? 0) === 0 && (summary.paidLast30Count ?? 0) === 0) {
    const empty = {
      headline: 'No AR activity yet',
      narrative: 'There aren’t any open or recently-paid invoices for this organisation. Once invoices start flowing through Xero, this briefing will surface what needs your attention.',
      actions: [],
      riskLevel: 'low' as const,
      generatedAt: new Date().toISOString(),
      cached: false,
    }
    kvPut(event, cacheKey, empty, 60 * 60)
    return empty
  }

  const payload: BriefingPayload = {
    outstandingTotal: summary.outstandingTotal,
    outstandingCount: summary.outstandingCount,
    overdueTotal: summary.overdueTotal,
    overdueCount: summary.overdueCount,
    dso30: summary.dso30,
    notSentCount: summary.notSentCount,
    notSentTotal: summary.notSentTotal,
    paidLast30Total: summary.paidLast30Total,
    avgDaysToPay: summary.avgDaysToPay,
    concentration: summary.concentration,
    topCustomers: summary.topCustomers,
    latePayers: summary.latePayers,
    cashForecast: summary.cashForecast,
    recurringMrr: 0, // optional — page enriches separately
    creditNotesTotal: 0, // optional
  }

  let parsed: any | null = null
  try {
    const raw = await generateModelRoutedGroqInsight(buildPrompt(payload), {
      defaultModelId: GROQ_MODELS.REASONING_120B, // best JSON adherence + reasoning; the briefing
                                                 // drives owner decisions, worth the extra tokens
      temperature: 0.2,
      maxTokens: 800,
      systemPrompt: SYSTEM_PROMPT,
      featureKey: 'xero_invoice_ai_briefing',
      metadata: {
        route: '/api/xero/invoices/ai-briefing',
        tenantId,
        refresh,
      },
    })
    parsed = tryParseJson(raw)
  } catch (err: any) {
    console.error('[ai-briefing] Groq call failed:', err?.message || err)
  }

  if (!parsed?.headline || typeof parsed?.narrative !== 'string') {
    // Graceful degrade — surface a deterministic summary instead of a 500.
    parsed = {
      headline: 'AI briefing unavailable right now',
      narrative: 'The AI service did not return a usable response. The numbers below are still accurate; refresh in a minute to retry.',
      actions: [],
      riskLevel: 'low',
    }
  }

  const result = {
    headline: String(parsed.headline).slice(0, 120),
    narrative: String(parsed.narrative).slice(0, 800),
    actions: Array.isArray(parsed.actions)
      ? parsed.actions.slice(0, 2).map((a: any) => ({
          label: String(a?.label ?? '').slice(0, 140),
          why: a?.why ? String(a.why).slice(0, 200) : undefined,
        })).filter((a: any) => a.label)
      : [],
    riskLevel: ['low', 'moderate', 'high'].includes(parsed.riskLevel) ? parsed.riskLevel : 'low',
    generatedAt: new Date().toISOString(),
    cached: false,
  }

  // Cache for 1 hour — long enough to avoid burning tokens on page loads,
  // short enough that a manual refresh button feels live.
  kvPut(event, cacheKey, result, 60 * 60)

  return result
})
