name = "banner-rooms-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{ name = "BANNER_ROOMS", class_name = "BannerRoom" }]

[[migrations]]
tag = "v1"
new_classes = ["BannerRoom"]
