/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 53be441c27839db7edd7323013cb71b3)
interface __BaseEnv_Env {
	EMAIL_QUARANTINE_BUCKET: R2Bucket;
	AI: Ai;
	APPLICATION_ORIGIN: "https://agency-dashboard-6cm.pages.dev";
	EMAIL_INGEST_HMAC_SECRET: string;
	EMAIL_QUARANTINE_ENCRYPTION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APPLICATION_ORIGIN" | "EMAIL_INGEST_HMAC_SECRET" | "EMAIL_QUARANTINE_ENCRYPTION_SECRET">> {}
}
