[build]
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "22"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Redirect all other requests to the serverless function for SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
