[build]
  command = "pnpm build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22"
  PNPM_FLAGS = "--shamefully-hoist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Redirect all other requests to the serverless function for SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# Security headers
[[headers]]
  for = "/**"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
