-- 209_campaign_action_log_budget_key.sql
-- Canonical active-action dedupe key for campaign budget changes.
--
-- The key is generated by server/utils/campaignBudgetIdentity.ts and represents:
-- tenant, client, platform, account, campaign external id, and period. Keeping it
-- on campaign_action_log lets Postgres block concurrent duplicate planned,
-- approved, or executing budget actions even when two requests race past the
-- API pre-check.

ALTER TABLE campaign_action_log
  ADD COLUMN IF NOT EXISTS budget_key TEXT;

UPDATE campaign_action_log
SET budget_key = NULLIF(metadata->>'budgetKey', '')
WHERE budget_key IS NULL
  AND metadata ? 'budgetKey';

CREATE UNIQUE INDEX IF NOT EXISTS idx_campaign_action_log_active_budget_key
  ON campaign_action_log (action_type, budget_key)
  WHERE budget_key IS NOT NULL
    AND action_type = 'budget_update'
    AND action_status IN ('planned', 'approved', 'executing');

CREATE INDEX IF NOT EXISTS idx_campaign_action_log_budget_key_lifecycle
  ON campaign_action_log (
    budget_key,
    COALESCE(executed_at, cancelled_at, approved_at, requested_at) DESC
  )
  WHERE budget_key IS NOT NULL;
