/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.staging.jsonc --include-runtime=false --env-interface=ManagementStagingEnv worker-staging.d.ts` (hash: b0783c66c0343760e115ccce8a79a991)
interface __BaseEnv_ManagementStagingEnv {
	HYPERDRIVE_FRESH: Hyperdrive;
	PAGE_STUDIO_RELEASE_ENVIRONMENT: "staging";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ManagementStagingEnv {}
}
interface ManagementStagingEnv extends __BaseEnv_ManagementStagingEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PAGE_STUDIO_RELEASE_ENVIRONMENT">> {}
}

// Keep sibling deployment declarations module-local. Binding types above are generated.
export type { ManagementStagingEnv }
