/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.production.jsonc --include-runtime=false --env-interface=ManagementProductionEnv worker-production.d.ts` (hash: 78f561db48599bdcca234d5dfde5024c)
interface __BaseEnv_ManagementProductionEnv {
	PAGE_STUDIO_CHECKPOINTS: R2Bucket;
	HYPERDRIVE_FRESH: Hyperdrive;
	PAGE_STUDIO_RELEASE_ENVIRONMENT: "production";
	PAGE_STUDIO_CLOUDFLARE_ACCOUNT_ID: "a5b299b3ad15c1b5b895dc66f9357b17";
	PAGE_STUDIO_CLOUDFLARE_ZONE_ID: "8e38cbf3910d291dd218710296661073";
	PAGE_STUDIO_CLIENT_STAGING: Fetcher /* xeroflow-page-studio-client-staging */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ManagementProductionEnv {}
}
interface ManagementProductionEnv extends __BaseEnv_ManagementProductionEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PAGE_STUDIO_RELEASE_ENVIRONMENT" | "PAGE_STUDIO_CLOUDFLARE_ACCOUNT_ID" | "PAGE_STUDIO_CLOUDFLARE_ZONE_ID">> {}
}

// Keep sibling deployment declarations module-local. Binding types above are generated.
export type { ManagementProductionEnv }
