/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.production.jsonc --include-runtime=false --env-interface=ManagementProductionEnv worker-production.d.ts` (hash: 00157c8cb61dae20578c8cf808e19d79)
interface __BaseEnv_ManagementProductionEnv {
	HYPERDRIVE_FRESH: Hyperdrive;
	PAGE_STUDIO_RELEASE_ENVIRONMENT: "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ManagementProductionEnv {}
}
interface ManagementProductionEnv extends __BaseEnv_ManagementProductionEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PAGE_STUDIO_RELEASE_ENVIRONMENT">> {}
}

// Keep sibling deployment declarations module-local. Binding types above are generated.
export type { ManagementProductionEnv }
