/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 756b137f14dc26e8f2f7da4cfd12071d)
interface __BaseEnv_Env {
	DASHBOARD_ORIGIN: "https://preview.agency-dashboard-6cm.pages.dev" | "https://app.xeroflow.io";
	PAGE_STUDIO_CONTROL_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		DASHBOARD_ORIGIN: "https://preview.agency-dashboard-6cm.pages.dev";
		PAGE_STUDIO_CONTROL_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DASHBOARD_ORIGIN" | "PAGE_STUDIO_CONTROL_SECRET">> {}
}
