/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 9b3e743ea50e42eaa92088760248e841)
interface __BaseEnv_Env {
	DASHBOARD_ORIGIN: "https://preview.agency-dashboard-6cm.pages.dev" | "https://app.xeroflow.io";
	CONTENT_COMPLETION_TRANSPORT?: "management-rpc";
	PAGE_STUDIO_CONTROL_SECRET: string;
	PAGE_STUDIO_MANAGEMENT_COMPLETION?: Service /* entrypoint ContentAttachmentAuthority from xeroflow-page-studio-management-staging */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		DASHBOARD_ORIGIN: "https://preview.agency-dashboard-6cm.pages.dev";
		CONTENT_COMPLETION_TRANSPORT: "management-rpc";
		PAGE_STUDIO_CONTROL_SECRET: string;
		PAGE_STUDIO_MANAGEMENT_COMPLETION: Service /* entrypoint ContentAttachmentAuthority from xeroflow-page-studio-management-staging */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DASHBOARD_ORIGIN" | "CONTENT_COMPLETION_TRANSPORT" | "PAGE_STUDIO_CONTROL_SECRET">> {}
}
