export const CRM_SEARCH_MARKETING_COPY = Object.freeze({
  featureTitle: 'Controlled CRM Search',
  featureCardDescription: 'Visible CRM search uses keyword ranking. Semantic assistance for people, companies, and opportunities is limited to approved agency-assistant contexts and is off by default.',
  featureDescription: 'Visible CRM search uses deterministic keyword ranking. Semantic assistance is limited to approved agency-assistant contexts, covers people, companies, and opportunities, and is off by default.',
  featureDetails: Object.freeze([
    Object.freeze({
      title: 'Visible Keyword Ranking',
      content: 'Agency CRM search and portal CRM search remain deterministic keyword ranking surfaces. Portal semantic ranking is unavailable, and enabling controlled assistance never changes the visible keyword contract.'
    }),
    Object.freeze({
      title: 'Controlled Agency-Assistant Assist',
      content: 'Semantic retrieval is limited to approved agency-assistant contexts and only people, companies, and opportunities are eligible. It is off by default and can enter assist only after evaluation, approval, fresh authorization, and budget checks succeed.'
    }),
    Object.freeze({
      title: 'Authorization Before Fusion',
      content: 'Vector candidates are treated as untrusted identifiers. Current PostgreSQL authorization and record state are checked before controlled hybrid retrieval can fuse semantic candidates with the complete keyword pool; content always comes from the authorized database row.'
    }),
    Object.freeze({
      title: 'Confirmed, Eventually Consistent Indexing',
      content: 'Authorized indexing is durable and asynchronous when enabled. A CRM record is eligible for semantic assistance only after its current revision reaches confirmed index state; accepted work is not treated as fresh, and indexing is neither universal nor continuously active.'
    })
  ]),
  navigationTitle: 'Controlled CRM Search',
  navigationSubtitle: 'Controlled agency-assistant retrieval'
})

export const CRM_SEARCH_MARKETING_SURFACE_CEILINGS = Object.freeze({
  agency_global: 'shadow',
  portal_global: 'off',
  agency_ai: 'assist'
} as const)

interface MarketingSurfaceClaim {
  key: string
  userSurface: string
  maximumMode: string
}

export function assertMarketingClaimSurfaceCeilings(claims: readonly MarketingSurfaceClaim[]): void {
  for (const claim of claims) {
    const exactCeiling = CRM_SEARCH_MARKETING_SURFACE_CEILINGS[
      claim.userSurface as keyof typeof CRM_SEARCH_MARKETING_SURFACE_CEILINGS
    ]
    if (exactCeiling && claim.maximumMode !== exactCeiling) {
      throw new Error(`${claim.key} uses ${claim.userSurface} with ${claim.maximumMode}; exact ceiling is ${exactCeiling}`)
    }
  }
}

export const CRM_SEARCH_MARKETING_CLAIMS = Object.freeze({
  visibleRanking: 'keyword',
  semanticSurface: 'agency_ai_assist',
  defaultMode: 'off',
  portalSemanticRanking: false,
  freshness: 'after_confirmed_indexing',
  semanticEntitySet: Object.freeze(['person', 'company', 'opportunity']),
  surfaceCeilings: CRM_SEARCH_MARKETING_SURFACE_CEILINGS,
  claims: Object.freeze([
    {
      key: 'features.catalogue.crm_search_agency',
      sourcePath: 'app/pages/features/index.vue',
      route: '/features',
      location: 'feature_catalog',
      renderedText: 'Visible CRM search uses keyword ranking.',
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.featureCardDescription',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_global',
      maximumMode: 'shadow',
      rolloutState: 'off_by_default'
    },
    {
      key: 'features.catalogue.crm_search_assist',
      sourcePath: 'app/pages/features/index.vue',
      route: '/features',
      location: 'feature_catalog',
      renderedText: 'Semantic assistance is limited to approved agency-assistant contexts and is off by default.',
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.featureCardDescription',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'features.catalogue.smart_watch',
      sourcePath: 'app/pages/features/index.vue',
      route: '/features',
      location: 'feature_catalog',
      renderedText: 'Semantic keyword subscriptions are a separate notification feature.',
      sourceNeedle: 'semantic keyword subscriptions across every board',
      entitySet: ['board_notification'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.catalogue.composite_scoring',
      sourcePath: 'app/pages/features/index.vue',
      route: '/features',
      location: 'feature_catalog',
      renderedText: 'Composite scoring is a separate AI-context feature.',
      sourceNeedle: 'Five-signal retrieval formula — semantic',
      entitySet: ['ai_context'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.crm_search_title',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/semantic-search',
      location: 'feature_catalog',
      renderedText: CRM_SEARCH_MARKETING_COPY.featureTitle,
      routeNeedle: CRM_SEARCH_MARKETING_COPY.featureTitle,
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.featureTitle',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_global',
      maximumMode: 'shadow',
      rolloutState: 'off_by_default'
    },
    {
      key: 'features.detail.crm_search_agency',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/semantic-search',
      location: 'rendered_text',
      renderedText: 'Visible CRM search uses deterministic keyword ranking.',
      routeNeedle: 'Visible CRM search uses deterministic keyword ranking.',
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.featureDescription',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_global',
      maximumMode: 'shadow',
      rolloutState: 'off_by_default'
    },
    {
      key: 'features.detail.crm_search_assist',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/semantic-search',
      location: 'rendered_text',
      renderedText: 'Semantic assistance is limited to approved agency-assistant contexts and is off by default.',
      routeNeedle: 'Semantic assistance is limited to approved agency-assistant contexts',
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.featureDescription',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'features.detail.crm_search_sections_agency',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/semantic-search',
      location: 'rendered_text',
      renderedText: CRM_SEARCH_MARKETING_COPY.featureDetails[0]?.content ?? '',
      routeNeedle: 'Visible Keyword Ranking',
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.featureDetails',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_global',
      maximumMode: 'shadow',
      rolloutState: 'off_by_default'
    },
    {
      key: 'features.detail.crm_search_sections_portal',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/semantic-search',
      location: 'rendered_text',
      renderedText: 'Portal semantic ranking is unavailable.',
      routeNeedle: 'Portal semantic ranking is unavailable',
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.featureDetails',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'portal_global',
      maximumMode: 'off',
      rolloutState: 'unavailable'
    },
    {
      key: 'features.detail.crm_search_sections_assist',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/semantic-search',
      location: 'rendered_text',
      renderedText: CRM_SEARCH_MARKETING_COPY.featureDetails.slice(1).map(detail => `${detail.title}: ${detail.content}`).join(' '),
      routeNeedle: 'Confirmed, Eventually Consistent Indexing',
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.featureDetails',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'features.detail.ai_chat_context',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/ai-chat',
      location: 'feature_catalog',
      renderedText: 'Existing AI chat context scoring is separate from CRM search.',
      routeNeedle: 'composite scoring system that combines semantic similarity',
      sourceNeedle: 'composite scoring system that combines semantic similarity',
      entitySet: ['ai_context'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.intent_classifier',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/intent-classification',
      location: 'feature_catalog',
      renderedText: 'Intent classification is a separate existing feature.',
      routeNeedle: 'weights for semantic similarity, recency, importance',
      sourceNeedle: 'weights for semantic similarity, recency, importance',
      entitySet: ['ai_intent'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.smart_watch_summary',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/smart-watch',
      location: 'feature_catalog',
      renderedText: 'Smart Watch semantic keyword subscriptions remain a separate feature.',
      routeNeedle: 'semantic keyword watch',
      sourceNeedle: 'semantic keyword watch',
      entitySet: ['board_notification'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.smart_watch_title',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/smart-watch',
      location: 'feature_catalog',
      renderedText: 'Semantic keyword subscriptions',
      routeNeedle: 'Semantic keyword subscriptions',
      sourceNeedle: 'title: \'Semantic keyword subscriptions\'',
      entitySet: ['board_notification'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.smart_watch_subscription',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/smart-watch',
      location: 'feature_catalog',
      renderedText: 'Smart Watch uses its own Workers AI and Vectorize notification path.',
      routeNeedle: 'every keyword is embedded with Workers AI',
      sourceNeedle: 'every keyword is embedded with Workers AI',
      entitySet: ['board_notification'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.composite_summary',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/composite-scoring',
      location: 'feature_catalog',
      renderedText: 'Composite AI-context scoring remains separate from CRM search.',
      routeNeedle: 'blends semantic similarity, recency',
      sourceNeedle: 'blends semantic similarity, recency',
      entitySet: ['ai_context'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.composite_formula',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/composite-scoring',
      location: 'feature_catalog',
      renderedText: 'Existing AI-context scoring may use Vectorize.',
      routeNeedle: 'semantic similarity (Vectorize cosine distance)',
      sourceNeedle: 'semantic similarity (Vectorize cosine distance)',
      entitySet: ['ai_context'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.composite_profiles',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/composite-scoring',
      location: 'feature_catalog',
      renderedText: 'Existing AI-context profiles are not visible CRM ranking.',
      routeNeedle: 'Process queries emphasise semantic similarity',
      sourceNeedle: 'Process queries emphasise semantic similarity',
      entitySet: ['ai_context'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.semantic_reranking_title',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/composite-scoring',
      location: 'feature_catalog',
      renderedText: 'Semantic Reranking',
      routeNeedle: 'Semantic Reranking',
      sourceNeedle: 'title: \'Semantic Reranking\'',
      entitySet: ['ai_context'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.composite_reranking',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/composite-scoring',
      location: 'feature_catalog',
      renderedText: 'Legacy AI-context reranking is separate from controlled CRM retrieval.',
      routeNeedle: 'Items sourced from the database are reranked by Vectorize',
      sourceNeedle: 'Items sourced from the database are reranked by Vectorize',
      entitySet: ['ai_context'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.knowledge_upload',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/knowledge-base',
      location: 'feature_catalog',
      renderedText: 'Knowledge uploads use their own existing Vectorize path.',
      routeNeedle: 'queues entries for Vectorize embedding',
      sourceNeedle: 'queues entries for Vectorize embedding',
      entitySet: ['knowledge_entry'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.vectorize_deduplication_title',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/knowledge-base',
      location: 'feature_catalog',
      renderedText: 'Vectorize Deduplication',
      routeNeedle: 'Vectorize Deduplication',
      sourceNeedle: 'title: \'Vectorize Deduplication\'',
      entitySet: ['knowledge_entry'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.knowledge_deduplication',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/knowledge-base',
      location: 'feature_catalog',
      renderedText: 'Knowledge deduplication is separate from CRM search.',
      routeNeedle: 'checks for semantic duplicates using Vectorize',
      sourceNeedle: 'checks for semantic duplicates using Vectorize',
      entitySet: ['knowledge_entry'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.knowledge_lifecycle',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/knowledge-base',
      location: 'feature_catalog',
      renderedText: 'Knowledge lifecycle cleanup is separate from CRM search.',
      routeNeedle: 'delete entries with Vectorize cleanup',
      sourceNeedle: 'delete entries with Vectorize cleanup',
      entitySet: ['knowledge_entry'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'features.detail.rate_card_context',
      sourcePath: 'app/pages/features/[slug].vue',
      route: '/features/rate-cards',
      location: 'feature_catalog',
      renderedText: 'Rate-card AI context is separate from CRM search.',
      routeNeedle: 'embedded in the vector database so pricing information',
      sourceNeedle: 'embedded in the vector database so pricing information',
      entitySet: ['rate_card'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'assist',
      rolloutState: 'available'
    },
    {
      key: 'navigation.crm_search',
      sourcePath: 'app/components/MarketingNav.vue',
      route: 'component:MarketingNav',
      location: 'navigation',
      renderedText: `${CRM_SEARCH_MARKETING_COPY.navigationTitle}: ${CRM_SEARCH_MARKETING_COPY.navigationSubtitle}`,
      sourceNeedle: 'CRM_SEARCH_MARKETING_COPY.navigationSubtitle',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'platform.ai.hero',
      sourcePath: 'app/pages/platform/ai.vue',
      route: '/platform/ai',
      location: 'rendered_text',
      renderedText: 'Visible CRM keyword search; controlled semantic assistance is off by default.',
      sourceNeedle: 'visible CRM keyword search. Controlled CRM semantic assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'platform.ai.agency_boundary',
      sourcePath: 'app/pages/platform/ai.vue',
      route: '/platform/ai',
      location: 'rendered_text',
      renderedText: 'Visible agency CRM ranking stays keyword-based.',
      sourceNeedle: 'Visible agency and portal CRM search remains keyword-ranked',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_global',
      maximumMode: 'shadow',
      rolloutState: 'controlled'
    },
    {
      key: 'platform.ai.portal_boundary',
      sourcePath: 'app/pages/platform/ai.vue',
      route: '/platform/ai',
      location: 'rendered_text',
      renderedText: 'Portal CRM ranking stays keyword-based and semantic ranking is unavailable.',
      sourceNeedle: 'Visible agency and portal CRM search remains keyword-ranked',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'portal_global',
      maximumMode: 'off',
      rolloutState: 'controlled'
    },
    {
      key: 'platform.ai.confirmed_state',
      sourcePath: 'app/pages/platform/ai.vue',
      route: '/platform/ai',
      location: 'rendered_text',
      renderedText: 'Only confirmed current records can contribute to controlled assist.',
      sourceNeedle: 'only records at confirmed index state',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'platform.ai.rate_cards',
      sourcePath: 'app/pages/platform/ai.vue',
      route: '/platform/ai',
      location: 'feature_catalog',
      renderedText: 'Rate-card lookup is separate from CRM semantic assistance.',
      sourceNeedle: 'CRM semantic assistance does not broaden access',
      entitySet: ['rate_card'],
      userSurface: 'separate_existing_feature',
      maximumMode: 'off',
      rolloutState: 'available'
    },
    {
      key: 'platform.ai.controlled_candidates_title',
      sourcePath: 'app/pages/platform/ai.vue',
      route: '/platform/ai',
      location: 'feature_catalog',
      renderedText: 'Controlled Semantic Candidates',
      sourceNeedle: 'title: \'Controlled Semantic Candidates\'',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'platform.ai.vector_candidates',
      sourcePath: 'app/pages/platform/ai.vue',
      route: '/platform/ai',
      location: 'feature_catalog',
      renderedText: 'Vector candidates are authorized before keyword fusion.',
      sourceNeedle: 'Vectorize candidates are filtered by current authorization',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.ai.summary',
      sourcePath: 'app/pages/resources/ai-automation.vue',
      route: '/resources/ai-automation',
      location: 'rendered_text',
      renderedText: 'Visible keyword search with controlled CRM semantic assistance off by default.',
      sourceNeedle: 'visible keyword search, and controlled CRM semantic assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'resources.ai.agency_boundary',
      sourcePath: 'app/pages/resources/ai-automation.vue',
      route: '/resources/ai-automation',
      location: 'rendered_text',
      renderedText: 'Visible agency CRM ranking remains keyword-based.',
      sourceNeedle: 'Visible agency and portal CRM results use deterministic keyword ranking',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_global',
      maximumMode: 'shadow',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.ai.portal_boundary',
      sourcePath: 'app/pages/resources/ai-automation.vue',
      route: '/resources/ai-automation',
      location: 'rendered_text',
      renderedText: 'Portal CRM ranking remains keyword-only.',
      sourceNeedle: 'Visible agency and portal CRM results use deterministic keyword ranking',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'portal_global',
      maximumMode: 'off',
      rolloutState: 'unavailable'
    },
    {
      key: 'resources.ai.freshness',
      sourcePath: 'app/pages/resources/ai-automation.vue',
      route: '/resources/ai-automation',
      location: 'rendered_text',
      renderedText: 'Semantic eligibility follows confirmed indexing.',
      sourceNeedle: 'Authorized indexing is asynchronous',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.ai.integrations_link',
      sourcePath: 'app/pages/resources/ai-automation.vue',
      route: '/resources/ai-automation',
      location: 'rendered_text',
      renderedText: 'Vectorize is one named platform integration.',
      sourceNeedle: 'Groq, Vectorize, and 6 more platform integrations',
      entitySet: ['provider_disclosure'],
      userSurface: 'provider_disclosure',
      maximumMode: 'off',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.ai.seo',
      sourcePath: 'app/pages/resources/ai-automation.vue',
      route: '/resources/ai-automation',
      location: 'seo_description',
      renderedText: 'Controlled CRM semantic assistance, visible keyword search, and an off by default rollout.',
      sourceNeedle: 'description: \'How AI automation works alongside controlled CRM semantic assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'resources.ai.og',
      sourcePath: 'app/pages/resources/ai-automation.vue',
      route: '/resources/ai-automation',
      location: 'seo_og_description',
      renderedText: 'Controlled CRM semantic assistance, visible keyword search, and an off by default rollout.',
      sourceNeedle: 'ogDescription: \'How AI automation works alongside controlled CRM semantic assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'resources.integrations.infrastructure',
      sourcePath: 'app/pages/resources/integrations.vue',
      route: '/resources/integrations',
      location: 'rendered_text',
      renderedText: 'The dedicated CRM Vectorize index is reserved for controlled CRM assistance after authorized indexing.',
      sourceNeedle: 'dedicated CRM Vectorize index</strong> is reserved for controlled CRM semantic assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'resources.integrations.provider_badge',
      sourcePath: 'app/pages/resources/integrations.vue',
      route: '/resources/integrations',
      location: 'rendered_text',
      renderedText: 'Vectorize',
      sourceNeedle: '>Vectorize</span>',
      entitySet: ['provider_disclosure'],
      userSurface: 'provider_disclosure',
      maximumMode: 'off',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.integrations.provider_heading',
      sourcePath: 'app/pages/resources/integrations.vue',
      route: '/resources/integrations',
      location: 'rendered_text',
      renderedText: 'Vectorize',
      sourceNeedle: '>Vectorize</h2>',
      entitySet: ['provider_disclosure'],
      userSurface: 'provider_disclosure',
      maximumMode: 'off',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.integrations.boundary',
      sourcePath: 'app/pages/resources/integrations.vue',
      route: '/resources/integrations',
      location: 'rendered_text',
      renderedText: 'Controlled CRM assist is off by default and requires confirmed indexing.',
      sourceNeedle: 'dedicated CRM Vectorize path is used only for controlled CRM semantic assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'resources.integrations.authorized_tag',
      sourcePath: 'app/pages/resources/integrations.vue',
      route: '/resources/integrations',
      location: 'rendered_text',
      renderedText: 'Authorized indexing',
      sourceNeedle: '>Authorized indexing</span>',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.integrations.summary',
      sourcePath: 'app/pages/resources/integrations.vue',
      route: '/resources/integrations',
      location: 'rendered_text',
      renderedText: 'Controlled CRM retrieval has separate rollout and indexing checks.',
      sourceNeedle: 'controlled CRM semantic assistance uses Workers AI and Vectorize',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.integrations.seo',
      sourcePath: 'app/pages/resources/integrations.vue',
      route: '/resources/integrations',
      location: 'seo_description',
      renderedText: 'Off-by-default Vectorize infrastructure for authorized confirmed CRM indexing.',
      sourceNeedle: 'description: \'XeroFlow integrations, including off-by-default Vectorize',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'resources.integrations.og',
      sourcePath: 'app/pages/resources/integrations.vue',
      route: '/resources/integrations',
      location: 'seo_og_description',
      renderedText: 'Off-by-default Vectorize infrastructure for authorized confirmed CRM indexing.',
      sourceNeedle: 'ogDescription: \'XeroFlow integrations, including off-by-default Vectorize',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'resources.index.guide',
      sourcePath: 'app/pages/resources/index.vue',
      route: '/resources',
      location: 'feature_catalog',
      renderedText: 'Controlled CRM retrieval through approved agency-assistant contexts.',
      sourceNeedle: 'controlled CRM retrieval through approved agency-assistant contexts',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'resources.index.vectorize',
      sourcePath: 'app/pages/resources/index.vue',
      route: '/resources',
      location: 'feature_catalog',
      renderedText: 'Vectorize: Controlled CRM assist',
      sourceNeedle: 'title: \'Vectorize\', icon: \'i-lucide-search\', status: \'Controlled CRM assist\'',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'landing.hero',
      sourcePath: 'app/pages/landing.vue',
      route: '/landing',
      location: 'rendered_text',
      renderedText: 'Visible CRM keyword search with controlled semantic assistance off by default.',
      sourceNeedle: 'visible CRM keyword search. Controlled semantic assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'landing.assistant_card',
      sourcePath: 'app/pages/landing.vue',
      route: '/landing',
      location: 'feature_catalog',
      renderedText: 'Visible CRM keyword search and controlled agency-assistant retrieval.',
      sourceNeedle: 'visible CRM keyword search, and controlled agency-assistant retrieval',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'landing.confirmed_index',
      sourcePath: 'app/pages/landing.vue',
      route: '/landing',
      location: 'feature_catalog',
      renderedText: 'Semantic assistance follows confirmed indexing.',
      sourceNeedle: 'after confirmed indexing',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'training.boundary',
      sourcePath: 'app/pages/ai-training.vue',
      route: '/ai-training',
      location: 'rendered_text',
      renderedText: 'Controlled CRM assistance is separate and requires confirmed index state.',
      sourceNeedle: 'Controlled CRM semantic assistance is separate',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'training.indexing',
      sourcePath: 'app/pages/ai-training.vue',
      route: '/ai-training',
      location: 'feature_catalog',
      renderedText: 'Controlled CRM Indexing',
      sourceNeedle: 'label: \'Controlled CRM Indexing\'',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'training.seo',
      sourcePath: 'app/pages/ai-training.vue',
      route: '/ai-training',
      location: 'seo_description',
      renderedText: 'Governed AI context and controlled CRM assistance are off by default.',
      sourceNeedle: 'description: \'Governed AI context and controlled CRM assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'training.og',
      sourcePath: 'app/pages/ai-training.vue',
      route: '/ai-training',
      location: 'seo_og_description',
      renderedText: 'Visible keyword search with controlled agency-assistant retrieval off by default.',
      sourceNeedle: 'ogDescription: \'Visible CRM keyword search with controlled agency-assistant retrieval',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'home.ai_summary',
      sourcePath: 'app/pages/index.vue',
      route: '/',
      location: 'rendered_text',
      renderedText: 'Visible CRM keyword search with approved agency-assistant semantic assistance.',
      sourceNeedle: 'visible CRM keyword search; semantic assistance',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'controlled'
    },
    {
      key: 'creativity.ai_summary',
      sourcePath: 'app/pages/creativity.vue',
      route: '/creativity',
      location: 'feature_catalog',
      renderedText: 'Controlled CRM semantic assistance is off by default.',
      sourceNeedle: 'controlled CRM semantic assistance, which is off by default',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'privacy.infrastructure',
      sourcePath: 'app/pages/privacy.vue',
      route: '/privacy',
      location: 'privacy_disclosure',
      renderedText: 'Cloudflare is an infrastructure and AI/Vectorize sub-processor.',
      sourceNeedle: 'AI inference, Vectorize',
      entitySet: ['provider_disclosure'],
      userSurface: 'privacy_disclosure',
      maximumMode: 'off',
      rolloutState: 'controlled'
    },
    {
      key: 'privacy.workers_ai',
      sourcePath: 'app/pages/privacy.vue',
      route: '/privacy',
      location: 'privacy_disclosure',
      renderedText: 'Workers AI embeddings are off by default.',
      sourceNeedle: 'Cloudflare Workers AI (controlled edge inference and CRM embeddings',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'privacy_disclosure',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'privacy.semantic_assist',
      sourcePath: 'app/pages/privacy.vue',
      route: '/privacy',
      location: 'privacy_disclosure',
      renderedText: 'Controlled CRM semantic assistance is off by default and uses scoped vectors.',
      sourceNeedle: 'Controlled CRM semantic assistance</strong>',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'privacy_disclosure',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'pricing.feature_list',
      sourcePath: 'app/_drafts/pricing-self-service.vue',
      route: 'draft:pricing-self-service',
      location: 'feature_catalog',
      renderedText: 'Controlled CRM assist (off by default)',
      sourceNeedle: 'Controlled CRM assist (off by default)',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    },
    {
      key: 'pricing.comparison',
      sourcePath: 'app/_drafts/pricing-self-service.vue',
      route: 'draft:pricing-self-service',
      location: 'feature_catalog',
      renderedText: 'Controlled CRM agency-assistant retrieval requires approval.',
      sourceNeedle: 'Controlled CRM agency-assistant retrieval (off by default)',
      entitySet: ['person', 'company', 'opportunity'],
      userSurface: 'agency_ai',
      maximumMode: 'assist',
      rolloutState: 'off_by_default'
    }
  ]),
  negativeAssertions: Object.freeze([
    { key: 'no_broad_vectorize', pattern: 'Vectorize-powered search across tasks, clients, briefs, and knowledge base entries' },
    { key: 'no_predictive_semantic', pattern: 'semantic search surface what matters before you even think to ask' },
    { key: 'no_unqualified_vectorize_training', pattern: 'semantic search via Vectorize[^\\n]*trained exclusively on your operations' },
    { key: 'no_continuous_learning', pattern: 'every chat, every decision, every workflow pattern makes your AI smarter[^\\n]*continuously' },
    { key: 'no_instant_natural_language', pattern: 'instant natural-language retrieval' },
    { key: 'no_fresh_index_claim', pattern: 'keeping the index (?:fresh|current)' },
    { key: 'no_continuous_index', pattern: 'continuously updated so search results reflect the latest data' },
    { key: 'no_auto_embedding', pattern: 'automatically embedded when created or updated' },
    { key: 'no_maintenance_free_index', pattern: 'no manual indexing or maintenance required' },
    { key: 'no_all_entity_search', pattern: 'search across all entity types simultaneously' },
    { key: 'no_better_recall_claim', pattern: 'hybrid approach delivers better recall than either method alone' },
    { key: 'no_universal_embedding_disclosure', pattern: 'text embeddings are generated to enable vector-based search across your data' },
    { key: 'no_broad_crm_entity_set', pattern: 'tasks, briefs, clients, and spend data' },
    { key: 'no_broad_embedded_entity_set', pattern: 'tasks, clients, briefs, and knowledge base entries are embedded as vectors' },
    { key: 'no_unqualified_training_seo', pattern: 'Your agency AI, trained on your data' },
    { key: 'no_unqualified_learning_seo', pattern: 'XeroFlow learns from your unique workflows, clients, and operations' },
    { key: 'no_continuous_training_og', pattern: 'Private, continuous, and entirely under your control' }
  ])
})

assertMarketingClaimSurfaceCeilings(CRM_SEARCH_MARKETING_CLAIMS.claims)
