/**
 * GET /api/xero/get-out/recurring-mix
 *
 * % of this month's invoiced revenue that came from active recurring
 * schedules (retainers / subscriptions). Industry target per Parakeeto:
 * 50-60%+ for a healthy agency.
 *
 * Computes: for each invoice this month, was it generated by a Xero
 * RepeatingInvoice schedule? (We approximate via the contact_id having
 * an active recurring schedule + the invoice landing close to a
 * scheduled date — a fuller version would join repeating_invoice_id
 * directly, but Xero's invoice payload makes that available so we use
 * the contact-level proxy when available in cache.)
 *
 * Simplest accurate approximation: sum MRR for contacts that invoiced
 * this month, capped at the invoiced amount per contact. Anything in
 * excess of MRR is project work. This matches what you'd intuitively
 * call "the retainer portion".
 */

import { defineEventHandler, createError } from 'h3'
import { requireAuth } from '~~/server/utils/auth'
import { queryRows } from '~~/server/utils/db'
import { getSelectedTenant } from '~~/server/utils/session'

interface ContactInvoicedRow {
  contact_id: string
  invoiced_cents: string | number
  mrr_cents: string | number | null
}

function n(v: unknown): number {
  if (v == null) return 0
  const num = typeof v === 'number' ? v : Number(v)
  return Number.isFinite(num) ? num : 0
}

export default defineEventHandler(async (event) => {
  await requireAuth(event)
  const tenantId = await getSelectedTenant(event)
  if (!tenantId) {
    throw createError({ statusCode: 400, statusMessage: 'No organization selected' })
  }

  const today = new Date()
  const monthStart = new Date(today.getFullYear(), today.getMonth(), 1).toISOString().slice(0, 10)
  const monthEnd = new Date(today.getFullYear(), today.getMonth() + 1, 0).toISOString().slice(0, 10)

  const rows = await queryRows<ContactInvoicedRow>(
    `SELECT i.contact_id,
            SUM(i.total_cents)::text AS invoiced_cents,
            cr.mrr_cents
       FROM xero_invoices_cache i
       LEFT JOIN xero_customer_rollups cr
         ON cr.tenant_id = i.tenant_id AND cr.contact_id = i.contact_id
       WHERE i.tenant_id = $1
         AND i.type = 'ACCREC'
         AND i.status NOT IN ('VOIDED','DRAFT','DELETED')
         AND i.date BETWEEN $2::date AND $3::date
       GROUP BY i.contact_id, cr.mrr_cents`,
    [tenantId, monthStart, monthEnd],
  )

  let totalRevenue = 0
  let recurringRevenue = 0
  let projectRevenue = 0
  let recurringClientCount = 0

  for (const r of rows) {
    const invoiced = n(r.invoiced_cents) / 100
    const mrr = n(r.mrr_cents) / 100
    totalRevenue += invoiced
    if (mrr > 0) {
      // Cap recurring contribution per contact at invoiced amount —
      // a contact's MRR can't exceed what we actually billed them.
      const recurringPortion = Math.min(mrr, invoiced)
      recurringRevenue += recurringPortion
      projectRevenue += invoiced - recurringPortion
      recurringClientCount++
    } else {
      projectRevenue += invoiced
    }
  }

  const recurringPct = totalRevenue > 0
    ? Math.round((recurringRevenue / totalRevenue) * 1000) / 10
    : 0

  // Health: target 50-60%+ per Parakeeto. <30% is "project shop", >70% is "agency-on-rails"
  let band: 'low' | 'mixed' | 'healthy' | 'high' = 'low'
  if (recurringPct >= 70) band = 'high'
  else if (recurringPct >= 50) band = 'healthy'
  else if (recurringPct >= 30) band = 'mixed'

  return {
    totalRevenue: Math.round(totalRevenue * 100) / 100,
    recurringRevenue: Math.round(recurringRevenue * 100) / 100,
    projectRevenue: Math.round(projectRevenue * 100) / 100,
    recurringPct,
    recurringClientCount,
    band,
  }
})
