/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.production.jsonc --include-runtime=false --env-interface=EmailRenderingProductionEnv worker-production.d.ts` (hash: 7f60e0265c52fea33210fcbaf3a44726)
interface __BaseEnv_EmailRenderingProductionEnv {
	EMAIL_RENDER_ENVIRONMENT: "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_EmailRenderingProductionEnv {}
}
interface EmailRenderingProductionEnv extends __BaseEnv_EmailRenderingProductionEnv {}

// Keep sibling deployment declarations module-local. Binding types above are generated.
export type { EmailRenderingProductionEnv }
