/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.staging.jsonc --include-runtime=false --env-interface=EmailRenderingStagingEnv worker-staging.d.ts` (hash: 1f4f30aa8bde9bc30a5ec5fc3262758a)
interface __BaseEnv_EmailRenderingStagingEnv {
	EMAIL_RENDER_ENVIRONMENT: "staging";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_EmailRenderingStagingEnv {}
}
interface EmailRenderingStagingEnv extends __BaseEnv_EmailRenderingStagingEnv {}

// Keep sibling deployment declarations module-local. Binding types above are generated.
export type { EmailRenderingStagingEnv }
