// server/utils/crm/oppQuote.ts
// F14 follow-up — generate a Pricing quote from a CRM opportunity's line-items.
// Additive to the Pricing module: writes the same `quotes` / `quote_line_items`
// tables the agency quote endpoints use, so the DB triggers auto-generate the
// quote_number and recompute quote totals (subtotal/discount/tax/total) on each
// item insert — we never compute totals here. The pure mappers below are unit-
// tested; createQuoteFromOpportunity is integration-probed.

import { queryOne, transaction } from '~~/server/utils/db'
import type { LineItemRow } from '~~/server/utils/crm/lineItemsDb'
import type { CrmSearchContext } from '~~/server/utils/crm/searchContext'
import { requireCrmRecordAccess, type TransactionClient } from '~~/server/utils/crm/recordAccess'

/** A quote line-item insert payload derived from a CRM opportunity line. */
export interface QuoteItemInsert {
  name: string
  quantity: number
  unitPrice: number
  lineTotal: number
  sortOrder: number
}

/** Quote title for an opportunity — its name, or a safe fallback. */
export function quoteTitleForOpp(opp: { name?: string | null }): string {
  return (opp.name ?? '').trim() || 'Opportunity quote'
}

/** Map CRM opportunity line-items to quote line-item insert payloads.
 *  description→name, qty/price copied (coerced from pg NUMERIC strings),
 *  line_total = qty*price (mirrors the generated column), position→sort_order. */
export function mapLineItemsToQuoteItems(
  items: Array<Pick<LineItemRow, 'description' | 'quantity' | 'unit_price' | 'position'>>,
): QuoteItemInsert[] {
  return items.map((it) => {
    const quantity = Number(it.quantity)
    const unitPrice = Number(it.unit_price)
    return {
      name: it.description,
      quantity,
      unitPrice,
      lineTotal: quantity * unitPrice,
      sortOrder: it.position,
    }
  })
}

/**
 * Create a draft quote from an opportunity + its line-items and atomically link
 * quote_id back onto the opportunity. Inserts the quote (quote_number auto-
 * generated by the BEFORE-INSERT trigger) and each line item (the
 * AFTER-INSERT trigger recomputes the quote totals) in ONE transaction — so a
 * mid-loop failure can't leave a partial/orphan quote — then returns the
 * re-fetched quote with the trigger-computed totals.
 */
export async function createQuoteFromOpportunity(input: {
  context?: CrmSearchContext
  opportunityId?: string
  clientId: string
  opp: { name?: string | null }
  items: QuoteItemInsert[]
  userId: string
}, deps: {
  transaction: <T>(callback: (db: TransactionClient) => Promise<T>) => Promise<T>
  queryOne: typeof queryOne
} = {
  transaction: transaction as <T>(callback: (db: TransactionClient) => Promise<T>) => Promise<T>,
  queryOne
}): Promise<Record<string, any>> {
  const title = quoteTitleForOpp(input.opp)
  const quoteId = await deps.transaction(async (db) => {
    let opportunityId = input.opportunityId
    if (input.context) {
      if (!opportunityId || input.context.clientId !== input.clientId) {
        throw createError({ statusCode: 404, statusMessage: 'Record not found' })
      }
      const record = await requireCrmRecordAccess(input.context, { type: 'opportunity', id: opportunityId }, db)
      if (record.row.quote_id) {
        throw createError({ statusCode: 409, statusMessage: 'This opportunity already has a linked quote — unlink it first.' })
      }
    }
    const res = await db.query(
      `INSERT INTO quotes (client_id, title, status, valid_from, currency, created_by, assigned_to)
       VALUES ($1, $2, 'draft', CURRENT_DATE, 'USD', $3, $3)
       RETURNING id`,
      [input.clientId, title, input.userId],
    )
    const qid = (res.rows?.[0] as { id?: string } | undefined)?.id
    if (!qid) throw createError({ statusCode: 500, statusMessage: 'Failed to create quote' })
    for (const item of input.items) {
      await db.query(
        `INSERT INTO quote_line_items
           (quote_id, item_type, name, quantity, unit, unit_price, discount_percent, line_total, sort_order, is_optional, is_included)
         VALUES ($1, 'service', $2, $3, 'unit', $4, 0, $5, $6, false, true)`,
        [qid, item.name, item.quantity, item.unitPrice, item.lineTotal, item.sortOrder],
      )
    }
    if (input.context && opportunityId) {
      const linked = await db.query(
        `UPDATE crm_opportunities SET quote_id = $1, updated_at = NOW()
          WHERE id = $2 AND client_id = $3 AND quote_id IS NULL RETURNING id`,
        [qid, opportunityId, input.context.clientId]
      )
      if (!linked.rows?.length) {
        throw createError({ statusCode: 409, statusMessage: 'This opportunity already has a linked quote — unlink it first.' })
      }
    }
    return qid
  })

  // Re-fetch (post-commit) so the trigger-computed totals are reflected.
  const fresh = await deps.queryOne<Record<string, any>>(`SELECT * FROM quotes WHERE id = $1`, [quoteId])
  if (!fresh) throw createError({ statusCode: 500, statusMessage: 'Failed to create quote' })
  return fresh
}
