// server/utils/crm/oppQuote.ts
// F14 follow-up — generate a Pricing quote from a CRM opportunity's line-items.
// Additive to the Pricing module: writes the same `quotes` / `quote_line_items`
// tables the agency quote endpoints use, so the DB triggers auto-generate the
// quote_number and recompute quote totals (subtotal/discount/tax/total) on each
// item insert — we never compute totals here. The pure mappers below are unit-
// tested; createQuoteFromOpportunity is integration-probed.

import { queryOne, transaction } from '~~/server/utils/db'
import type { LineItemRow } from '~~/server/utils/crm/lineItemsDb'

/** A quote line-item insert payload derived from a CRM opportunity line. */
export interface QuoteItemInsert {
  name: string
  quantity: number
  unitPrice: number
  lineTotal: number
  sortOrder: number
}

/** Quote title for an opportunity — its name, or a safe fallback. */
export function quoteTitleForOpp(opp: { name?: string | null }): string {
  return (opp.name ?? '').trim() || 'Opportunity quote'
}

/** Map CRM opportunity line-items to quote line-item insert payloads.
 *  description→name, qty/price copied (coerced from pg NUMERIC strings),
 *  line_total = qty*price (mirrors the generated column), position→sort_order. */
export function mapLineItemsToQuoteItems(
  items: Array<Pick<LineItemRow, 'description' | 'quantity' | 'unit_price' | 'position'>>,
): QuoteItemInsert[] {
  return items.map((it) => {
    const quantity = Number(it.quantity)
    const unitPrice = Number(it.unit_price)
    return {
      name: it.description,
      quantity,
      unitPrice,
      lineTotal: quantity * unitPrice,
      sortOrder: it.position,
    }
  })
}

/**
 * Create a draft quote from an opportunity + its line-items, link nothing here
 * (the caller links quote_id back onto the opp). Inserts the quote (quote_number
 * auto-generated by the BEFORE-INSERT trigger) and each line item (the
 * AFTER-INSERT trigger recomputes the quote totals) in ONE transaction — so a
 * mid-loop failure can't leave a partial/orphan quote — then returns the
 * re-fetched quote with the trigger-computed totals.
 */
export async function createQuoteFromOpportunity(input: {
  clientId: string
  opp: { name?: string | null }
  items: QuoteItemInsert[]
  userId: string
}): Promise<Record<string, any>> {
  const title = quoteTitleForOpp(input.opp)
  const quoteId = await transaction(async (db) => {
    const res = await db.query<{ id: string }>(
      `INSERT INTO quotes (client_id, title, status, valid_from, currency, created_by, assigned_to)
       VALUES ($1, $2, 'draft', CURRENT_DATE, 'USD', $3, $3)
       RETURNING id`,
      [input.clientId, title, input.userId],
    )
    const qid = res.rows[0]?.id
    if (!qid) throw createError({ statusCode: 500, statusMessage: 'Failed to create quote' })
    for (const item of input.items) {
      await db.query(
        `INSERT INTO quote_line_items
           (quote_id, item_type, name, quantity, unit, unit_price, discount_percent, line_total, sort_order, is_optional, is_included)
         VALUES ($1, 'service', $2, $3, 'unit', $4, 0, $5, $6, false, true)`,
        [qid, item.name, item.quantity, item.unitPrice, item.lineTotal, item.sortOrder],
      )
    }
    return qid
  })

  // Re-fetch (post-commit) so the trigger-computed totals are reflected.
  const fresh = await queryOne<Record<string, any>>(`SELECT * FROM quotes WHERE id = $1`, [quoteId])
  if (!fresh) throw createError({ statusCode: 500, statusMessage: 'Failed to create quote' })
  return fresh
}
