import { beforeEach, describe, expect, it, vi } from 'vitest'
const m = vi.hoisted(() => ({ write: vi.fn(), role: vi.fn(), access: vi.fn(), manage: vi.fn(), read: vi.fn(), delete: vi.fn() }))
vi.mock('~~/server/utils/auth', () => ({ requireWriteAccess: m.write, requireRole: m.role }))
vi.mock('~~/server/utils/socialPublishing/guards', () => ({ requireSocialPostClientAccess: m.access }))
vi.mock('~~/server/utils/socialPublishing/liveOperations', () => ({ manageLiveFacebook: m.manage, readLiveFacebook: m.read }))
vi.mock('~~/server/utils/db', () => ({ queryOneFresh: m.delete }))
vi.stubGlobal('defineEventHandler', (fn: unknown) => fn)
vi.stubGlobal('getRouterParam', () => 'post')
vi.stubGlobal('getQuery', (e: { query: unknown }) => e.query)
vi.stubGlobal('readBody', (e: { body: unknown }) => e.body)
vi.stubGlobal('createError', (e: { statusMessage: string }) => new Error(e.statusMessage))
const { default: mutate } = await import('../../../server/api/agency/social/publishing/posts/[id]/live.post')
const { default: read } = await import('../../../server/api/agency/social/publishing/posts/[id]/live.get')
const { default: removeLocal } = await import('../../../server/api/agency/social/publishing/posts/[id]/index.delete')
const body = { accountId: '11111111-1111-4111-8111-111111111111', operationId: '22222222-2222-4222-8222-222222222222', action: 'edit', message: 'Revision', expectedMessage: 'Original', confirmed: true }
const run = (patch = {}) => mutate({ body: { ...body, ...patch } } as never)
beforeEach(() => { vi.resetAllMocks(); m.write.mockResolvedValue({ id: 'manager' }); m.access.mockResolvedValue({ id: 'post', client_id: 'client' }) })
describe('live management authority', () => {
  it('rejects viewers before mutation', async () => { m.write.mockRejectedValue(new Error('Read only')); await expect(run()).rejects.toThrow('Read only'); expect(m.manage).not.toHaveBeenCalled() })
  it('requires management before reading or writing provider data', async () => {
    m.role.mockRejectedValue(new Error('Management required'))
    await expect(run()).rejects.toThrow('Management required')
    await expect(read({ query: { accountId: body.accountId } } as never)).rejects.toThrow('Management required')
    expect(m.manage).not.toHaveBeenCalled(); expect(m.read).not.toHaveBeenCalled()
  })
  it('enforces client isolation', async () => { m.access.mockRejectedValue(new Error('Forbidden')); await expect(run()).rejects.toThrow('Forbidden'); expect(m.manage).not.toHaveBeenCalled() })
  it.each([{ confirmed: false }, { expectedMessage: undefined }, { message: '' }, { accountId: 'not-uuid' }, { action: 'unsupported' }, { providerId: '123_456' }])('rejects invalid or unconfirmed request %j', async patch => { await expect(run(patch)).rejects.toThrow('Review and confirm'); expect(m.manage).not.toHaveBeenCalled() })
  it('passes server-resolved client and actor', async () => { await run(); expect(m.manage).toHaveBeenCalledWith('post', 'client', 'manager', body) })
  it('rejects read-only local deletion', async () => { m.write.mockRejectedValue(new Error('Read only')); await expect(removeLocal({} as never)).rejects.toThrow('Read only'); expect(m.delete).not.toHaveBeenCalled() })
  it('preserves local published archive', async () => { m.delete.mockResolvedValue(null); await expect(removeLocal({} as never)).rejects.toThrow('archive'); expect(m.delete.mock.calls[0][0]).toContain("'published','partially_published','publishing'") })
})
