import { beforeEach, describe, expect, it, vi } from 'vitest'

const mocks = vi.hoisted(() => ({ role: vi.fn(), access: vi.fn(), transaction: vi.fn(), query: vi.fn() }))
vi.mock('~~/server/utils/auth', () => ({ requireRole: mocks.role }))
vi.mock('~~/server/utils/social/clientAccess', () => ({ requireSocialClientAccess: mocks.access }))
vi.mock('~~/server/utils/db', () => ({ transaction: mocks.transaction }))
vi.stubGlobal('defineEventHandler', (handler: unknown) => handler)
vi.stubGlobal('readBody', (event: { body: unknown }) => event.body)
vi.stubGlobal('createError', (input: { statusCode: number, statusMessage: string }) => Object.assign(new Error(input.statusMessage), input))
const { PERMISSIONS } = await import('../../../server/utils/permissions')
const { default: saveHandler } = await import('../../../server/api/agency/social/publishing/news-autopost/index.put')
const save = saveHandler as unknown as (event: { body: unknown }) => Promise<{ cancelled: number }>
const body = { clientId: 'bc8a15a8-f523-4a75-a8f4-a501649bb71d', accountId: '2b0d3667-d4c7-47d5-b685-58934dfdc5a3', mode: 'automatic' }
beforeEach(() => {
  vi.clearAllMocks()
  mocks.role.mockResolvedValue({ id: 'manager' })
  mocks.access.mockResolvedValue({ id: 'manager' })
  mocks.transaction.mockImplementation(fn => fn({ query: mocks.query }))
  mocks.query.mockImplementation(async (sql: string) => {
    if (sql.startsWith('SELECT * FROM social_news_autopost_rules')) return { rows: [{ id: 'rule', account_id: body.accountId, mode: 'automatic' }] }
    if (sql.startsWith('SELECT id FROM social_accounts')) return { rows: [{ id: body.accountId }] }
    if (sql.startsWith('INSERT INTO social_news_autopost_rules')) return { rows: [{ id: 'rule' }] }
    if (sql.startsWith('UPDATE social_posts')) return { rows: [{ id: 'auto' }] }
    return { rows: [] }
  })
})
describe('news auto-posting configuration', () => {
  it('requires management permission before granting automatic approval', async () => {
    await save({ body })
    expect(mocks.role.mock.calls[0][1]).toEqual(PERMISSIONS.MANAGEMENT)
    mocks.role.mockRejectedValue(new Error('Forbidden'))
    await expect(save({ body })).rejects.toThrow('Forbidden')
  })
  it('enforces client isolation before any database write', async () => {
    mocks.access.mockRejectedValue(new Error('No access to this client'))
    await expect(save({ body })).rejects.toThrow('No access')
    expect(mocks.transaction).not.toHaveBeenCalled()
  })
  it('rejects unsupported mode and target identities', async () => {
    await expect(save({ body: { ...body, mode: 'publish-anything' } })).rejects.toThrow('valid mode')
    expect(mocks.transaction).not.toHaveBeenCalled()
  })
  it('cancels only pending posts generated by this rule when paused', async () => {
    expect(await save({ body: { ...body, mode: 'paused' } })).toMatchObject({ cancelled: 1 })
    const update = mocks.query.mock.calls.find(call => String(call[0]).startsWith('UPDATE social_posts'))!
    expect(update[0]).toContain('status=\'scheduled\'')
    expect(update[0]).toContain('metadata->>\'newsAutopostAutomatic\'=\'true\'')
    expect(update[1]).toEqual([body.clientId, 'rule'])
  })
  it('reads the latest rule only after acquiring the shared client lock', async () => {
    await save({ body })
    expect(mocks.query.mock.calls[0][0]).toContain('pg_advisory_xact_lock')
    expect(mocks.query.mock.calls[1][0]).toContain('FOR UPDATE')
  })
})
