<script setup lang="ts">
import { computed } from 'vue'
import {
  normalizeEmailEndpointPrefixInput,
  type EmailEndpointClientOption,
  type EmailEndpointDraft,
  type SafeEmailLeadEndpoint
} from '~/utils/emailEndpointUi'

const props = defineProps<{
  endpoint: SafeEmailLeadEndpoint | null
  clients: EmailEndpointClientOption[]
}>()

const draft = defineModel<EmailEndpointDraft>({ required: true })
const isEditing = computed(() => Boolean(props.endpoint))
const addressPrefixLocked = computed(() => Boolean(props.endpoint?.last_received_at))
const clientOptions = computed(() => [
  { value: 'none', label: 'Select a client', disabled: true },
  ...props.clients.map(client => ({ value: client.id, label: client.name }))
])
const providerOptions = [
  { value: 'none', label: 'Any provider' },
  { value: 'carsales', label: 'Carsales' },
  { value: 'autotrader', label: 'Autotrader' },
  { value: 'carsguide', label: 'CarsGuide' },
  { value: 'drive', label: 'Drive' },
  { value: 'gumtree', label: 'Gumtree' },
  { value: 'google', label: 'Google' },
  { value: 'meta', label: 'Meta' },
  { value: 'instagram', label: 'Instagram' },
  { value: 'tiktok', label: 'TikTok' },
  { value: 'generic', label: 'Generic email' }
]

function updateAddressPrefix(value: string | number) {
  draft.value.addressPrefix = normalizeEmailEndpointPrefixInput(value)
}
</script>

<template>
  <section class="space-y-4" aria-labelledby="endpoint-details-heading">
    <div>
      <h2 id="endpoint-details-heading" class="text-sm font-semibold">
        Endpoint details
      </h2>
      <p class="text-sm text-muted">
        The address token is generated by the server and is never exposed separately.
      </p>
    </div>

    <div class="grid grid-cols-1 gap-4 @lg:grid-cols-2">
      <UFormField label="Client" required>
        <USelectMenu
          v-model="draft.clientId"
          :items="clientOptions"
          value-key="value"
          class="w-full"
          :disabled="isEditing"
        />
      </UFormField>

      <UFormField label="Label" required>
        <UInput
          v-model="draft.label"
          class="w-full"
          placeholder="e.g. Carsales NSW"
          autofocus
        />
      </UFormField>

      <UFormField
        label="Address prefix"
        :help="addressPrefixLocked ? 'Locked after the first message is received.' : 'Optional lower-case ASCII prefix.'"
      >
        <UInput
          :model-value="draft.addressPrefix"
          class="w-full"
          placeholder="e.g. carsales-nsw"
          :disabled="addressPrefixLocked"
          @update:model-value="updateAddressPrefix"
        />
      </UFormField>

      <UFormField label="Expected provider" help="Optional. Any provider is accepted by default.">
        <USelectMenu
          v-model="draft.expectedProvider"
          :items="providerOptions"
          value-key="value"
          class="w-full"
        />
      </UFormField>

      <UFormField label="Form name" required class="@lg:col-span-2">
        <UInput
          v-model="draft.formName"
          class="w-full"
          placeholder="e.g. Carsales enquiries"
        />
      </UFormField>
    </div>
  </section>
</template>
