/**
 * Duplicate a brief — creates a new draft copy with all field values.
 */

import { transaction } from '~~/server/utils/db'
import { requireWriteAccess } from '~~/server/utils/auth'

export default defineEventHandler(async (event) => {
  const user = await requireWriteAccess(event)
  const id = getRouterParam(event, 'id')

  if (!id) {
    throw createError({ statusCode: 400, statusMessage: 'Brief ID is required' })
  }

  try {
    return await transaction(async (db) => {
      const queryOne = async (sql: string, params: unknown[]) => (await db.query(sql, params)).rows[0]
      // Get original brief
      const original = await queryOne(`
      SELECT template_id, title, client_id, project_id, department_id,
             priority, requested_deadline, budget_min, budget_max,
             budget_currency, source
      FROM briefs
      WHERE id = $1 FOR SHARE
    `, [id])

      if (!original) {
        throw createError({ statusCode: 404, statusMessage: 'Brief not found' })
      }

      // Create duplicate as draft (reference_number generated by DB trigger)
      const newBrief = await queryOne(`
      INSERT INTO briefs (
        template_id, title, submitted_by, client_id, project_id,
        department_id, status, priority, requested_deadline,
        budget_min, budget_max, budget_currency, source
      ) VALUES ($1, $2, $3, $4, $5, $6, 'draft', $7, $8, $9, $10, $11, $12)
      RETURNING id, reference_number
    `, [
        original.template_id,
        `${original.title} (Copy)`,
        user.id,
        original.client_id,
        original.project_id,
        original.department_id,
        original.priority,
        original.requested_deadline,
        original.budget_min,
        original.budget_max,
        original.budget_currency || 'USD',
        original.source || 'internal'
      ])

      // Copy JSONB inside PostgreSQL: binding raw strings/arrays as JSONB can corrupt values.
      await db.query(`
      INSERT INTO brief_field_values (brief_id, field_id, value)
      SELECT $1, field_id, value FROM brief_field_values WHERE brief_id = $2
    `, [newBrief.id, id])

      // Log activity on new brief
      await db.query(`
      INSERT INTO brief_activities (brief_id, user_id, activity_type, content)
      VALUES ($1, $2, 'created', $3)
    `, [newBrief.id, user.id, `Duplicated from brief ${id}`])

      return {
        id: newBrief.id,
        referenceNumber: newBrief.reference_number
      }
    })
  } catch (error: unknown) {
    if (error && typeof error === 'object' && 'statusCode' in error) throw error
    console.error('Failed to duplicate brief:', error)
    throw createError({ statusCode: 500, statusMessage: 'Failed to duplicate brief' })
  }
})
