import type { VideoGenerationModel } from '~~/server/utils/video-generation/types'

const MODELS: VideoGenerationModel[] = [
  {
    id: 'mock/i2v-safe',
    provider: 'mock',
    displayName: 'Mock Safe Image-to-Video',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: false,
    durationsSeconds: [5, 10],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: ['720p'],
    estimatedCostCents: 50,
    costUnit: 'second',
    safetyClass: 'vehicle_i2v_safe',
    // Mock provider returns a fake mock.local URL that can't be downloaded — not selectable
    // in the picker (would always fail at finalize). Kept for tests/policy allow-lists.
    defaultEnabled: false,
  },
  {
    id: 'mock/t2v-broll',
    provider: 'mock',
    displayName: 'Mock Non-Vehicle Text-to-Video',
    modes: ['text-to-video'],
    allowedSubjectTypes: ['non_vehicle'],
    requiresApprovedSourceAsset: false,
    supportsNativeAudio: false,
    durationsSeconds: [5],
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p'],
    estimatedCostCents: 200,
    costUnit: 'generation',
    safetyClass: 'non_vehicle_t2v',
    defaultEnabled: false,
  },
  {
    id: 'aigateway/seedance-i2v',
    provider: 'aigateway',
    displayName: 'Seedance (image-to-video)',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: false,
    durationsSeconds: [5, 10],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 30,
    costUnit: 'second',
    safetyClass: 'vehicle_i2v_safe',
    defaultEnabled: true,
    cfModel: 'bytedance/seedance-2.0-fast',
    surface: 'tenant',
    modality: 'i2v',
  },
  {
    id: 'aigateway/wan-i2v',
    provider: 'aigateway',
    displayName: 'Wan 2.7 (image-to-video)',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: false,
    durationsSeconds: [5, 10],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 30,
    costUnit: 'second',
    safetyClass: 'vehicle_i2v_safe',
    defaultEnabled: true,
    cfModel: 'alibaba/wan-2.7-i2v',
    surface: 'tenant',
    modality: 'i2v',
  },
  {
    id: 'aigateway/hailuo-i2v',
    provider: 'aigateway',
    displayName: 'MiniMax Hailuo (image-to-video)',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: false,
    durationsSeconds: [5, 10],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 30,
    costUnit: 'second',
    safetyClass: 'vehicle_i2v_safe',
    defaultEnabled: true,
    cfModel: 'minimax/hailuo-2.3-fast',
    surface: 'tenant',
    modality: 'i2v',
  },
  {
    id: 'aigateway/runway-i2v',
    provider: 'aigateway',
    displayName: 'Runway Gen-4.5 (image-to-video)',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: false,
    durationsSeconds: [5, 10],
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 50,
    costUnit: 'second',
    safetyClass: 'vehicle_i2v_safe',
    defaultEnabled: true,
    cfModel: 'runwayml/gen-4.5',
    surface: 'tenant',
    modality: 'i2v',
  },
  {
    id: 'aigateway/vidu-i2v',
    provider: 'aigateway',
    displayName: 'Vidu Q3 (image-to-video)',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: true,
    durationsSeconds: [4, 8],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 25,
    costUnit: 'second',
    safetyClass: 'vehicle_i2v_safe',
    defaultEnabled: true,
    cfModel: 'vidu/q3-pro',
    surface: 'tenant',
    modality: 'i2v',
  },
  {
    id: 'aigateway/pixverse-i2v',
    provider: 'aigateway',
    displayName: 'PixVerse v5.6 (image-to-video)',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: true,
    durationsSeconds: [5, 8],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: ['540p', '720p', '1080p'],
    estimatedCostCents: 25,
    costUnit: 'second',
    safetyClass: 'vehicle_i2v_safe',
    defaultEnabled: true,
    cfModel: 'pixverse/v5.6',
    surface: 'tenant',
    modality: 'i2v',
  },
  {
    id: 'aigateway/veo-t2v',
    provider: 'aigateway',
    displayName: 'Veo 3.1 (text-to-video, with audio)',
    modes: ['text-to-video'],
    allowedSubjectTypes: ['non_vehicle'],
    requiresApprovedSourceAsset: false,
    supportsNativeAudio: true,
    durationsSeconds: [5, 8],
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 50,
    costUnit: 'second',
    safetyClass: 'non_vehicle_t2v',
    defaultEnabled: true,
    cfModel: 'google/veo-3.1-fast',
    surface: 'tenant',
    modality: 't2v',
  },
  {
    id: 'aigateway/hailuo-t2v',
    provider: 'aigateway',
    displayName: 'MiniMax Hailuo (text-to-video)',
    modes: ['text-to-video'],
    allowedSubjectTypes: ['non_vehicle'],
    requiresApprovedSourceAsset: false,
    supportsNativeAudio: false,
    durationsSeconds: [5, 10],
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 30,
    costUnit: 'second',
    safetyClass: 'non_vehicle_t2v',
    defaultEnabled: true,
    cfModel: 'minimax/hailuo-2.3',
    surface: 'tenant',
    modality: 't2v',
  },
  {
    id: 'aigateway/veo-t2v-internal',
    provider: 'aigateway',
    displayName: 'Veo (text-to-video, internal)',
    modes: ['text-to-video'],
    allowedSubjectTypes: ['non_vehicle'],
    requiresApprovedSourceAsset: false,
    supportsNativeAudio: true,
    durationsSeconds: [5, 8],
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p'],
    estimatedCostCents: 200,
    costUnit: 'second',
    safetyClass: 'non_vehicle_t2v',
    defaultEnabled: false,
    cfModel: 'google/veo-3.1',
    surface: 'internal',
    modality: 't2v',
  },
  {
    id: 'muapi/i2v-kling',
    provider: 'muapi',
    displayName: 'Kling Image-to-Video',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: false,
    durationsSeconds: [5, 10],
    aspectRatios: ['16:9', '9:16', '1:1'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 45,
    costUnit: 'second',
    safetyClass: 'vehicle_i2v_safe',
    defaultEnabled: false,
    muapi: { endpoint: 'generate_kling_i2v' },
  },
  {
    id: 'muapi/t2v-wan',
    provider: 'muapi',
    displayName: 'Wan Text-to-Video',
    modes: ['text-to-video'],
    allowedSubjectTypes: ['non_vehicle'],
    requiresApprovedSourceAsset: false,
    supportsNativeAudio: false,
    durationsSeconds: [5],
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p'],
    estimatedCostCents: 180,
    costUnit: 'generation',
    safetyClass: 'non_vehicle_t2v',
    defaultEnabled: false,
    muapi: { endpoint: 'generate_wan_t2v' },
  },
  {
    id: 'gateway/i2v-dormant',
    provider: 'gateway',
    displayName: 'Dormant Gateway Image-to-Video',
    modes: ['image-to-video'],
    allowedSubjectTypes: ['vehicle', 'non_vehicle'],
    requiresApprovedSourceAsset: true,
    supportsNativeAudio: true,
    durationsSeconds: [5, 10],
    aspectRatios: ['16:9', '9:16'],
    resolutions: ['720p', '1080p'],
    estimatedCostCents: 500,
    costUnit: 'second',
    safetyClass: 'disabled',
    defaultEnabled: false,
  },
]

export function listVideoGenerationModels(): VideoGenerationModel[] {
  return MODELS.map((model) => ({ ...model, modes: [...model.modes], allowedSubjectTypes: [...model.allowedSubjectTypes] }))
}

export function listSelectableVideoGenerationModels(): VideoGenerationModel[] {
  return listVideoGenerationModels().filter((model) => model.defaultEnabled && model.safetyClass !== 'disabled')
}

export function getVideoGenerationModel(id: string): VideoGenerationModel | null {
  const model = MODELS.find((candidate) => candidate.id === id)
  return model ? { ...model, modes: [...model.modes], allowedSubjectTypes: [...model.allowedSubjectTypes] } : null
}
